# User config
author: "Max Dovey"
tagline: ""
description: "This website has a selection of published projects spanning art projects, collective productions and work in education."
projects: "I design performative interactions between people and things and create participatory experiences that make use of networks, data, algorithms and computational culture.
My work looks at contemporary algorithmic culture through an embodied performative practice and documentation of some of my projects can be found below."
production: "I work as a freelance producer for both cultural and academic organisations and have organised workshops,symposiums, parties and festivals."
teaching: "I am pathway leader for MA Computational Art at Camberwell College of Arts and have delivered various guest workshops and short courses in creative technology."
keywords: "Data, Art, Performance, Experience"
email: "Dear@maxdovey.com"
linkedin: "https://www.are.na/max-dovey/"
twitter: "https://twitter.com/maxdovey"
github: "https://github.com/maxdovey/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
